vich_uploader:
    db_driver: orm

    mappings:
       location_images:
           uri_prefix: /images/locations
           upload_destination: '%kernel.project_dir%/public/images/locations'
           namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
